---
- name: Install required dependencies
  dnf:
    name:
      - curl
      - policycoreutils
      - openssh-server
      - perl
    state: present

- name: Enable and start SSH
  systemd:
    name: sshd
    state: started
    enabled: true

- name: Add GitLab CE repository
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
  args:
    creates: /etc/yum.repos.d/gitlab_gitlab-ce.repo

- name: Install GitLab CE
  dnf:
    name: gitlab-ce
    state: present

- name: Configure GitLab external URL
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: 'external_url "https://gitlab-maralex.duckdns.org/"'
    create: yes

- name: Add Redis and PostgreSQL configuration to gitlab.rb
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Redis & PostgreSQL config"
    block: |
      redis['enable'] = false

      # Default Redis connection
      gitlab_rails['redis_host'] = '51.38.239.212'
      gitlab_rails['redis_port'] = 6379
      gitlab_rails['redis_password'] = 'MAroot'

      # Set to true if instance is using Redis SSL
      gitlab_rails['redis_ssl'] = false

      nginx['listen_port'] = 80
      nginx['listen_https'] = false


      nginx['proxy_set_headers'] = {
        "Host" => "$http_host",
        "X-Real-IP" => "$remote_addr",
        "X-Forwarded-For" => "$proxy_add_x_forwarded_for",
        "X-Forwarded-Proto" => "https"
      }

      # Disable the bundled Omnibus provided PostgreSQL
    
      postgresql['enable'] = false

      # PostgreSQL connection details
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'unicode'
      gitlab_rails['db_host'] = '51.38.239.212'
      gitlab_rails['db_port'] = 5432
      gitlab_rails['db_password'] = 'MAroot'
      gitlab_rails['initial_root_password'] = "MartinAlex"
      gitlab_rails['initial_root_email'] = "root@gmail.com"
      gitlab_rails['time_zone'] = 'Europe/Paris'
      gitlab_rails['omniauth_enabled'] = true
      gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
      gitlab_rails['omniauth_block_auto_created_users'] = false
      gitlab_rails['trusted_proxies'] = ['51.38.232.14']
      
      gitlab_rails['omniauth_providers'] = [
        {
          name: "openid_connect", # do not change this parameter
          label: "Keycloak", # optional label for login button, defaults to "Openid Connect"
          args: {
            name: "openid_connect",
            scope: ["openid", "profile", "email"],
            response_type: "code",
            issuer:  "https://keycloak-maralex.duckdns.org/realms/master",
            client_auth_method: "query",
            discovery: true,
            uid_field: "preferred_username",
            pkce: true,
            client_options: {
              identifier: "gitlab",
              secret: "id2WAqrp1gRStdl0wV88YO87DfalODU5",
              redirect_uri: "https://gitlab-maralex.duckdns.org/users/auth/openid_connect/callback"
            }
          }
        }
      ]
      

# - name: Déployer la configuration de Redis
#   become: true
#   template:
#     src: gitlab.rb.j2
#     dest: /etc/gitlab/gitlab.rb
#     owner: root
#     group: root
#     mode: 0644

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure