---
  - name: Create user for Node Exporter
    user:
      name: "{{ node_exporter_user }}"
      shell: /usr/sbin/nologin
      system: yes
      create_home: no

  - name: Download Node Exporter archive
    get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: "/tmp/node_exporter.tar.gz"
      mode: '0644'

  - name: Extract Node Exporter binary
    unarchive:
      src: "/tmp/node_exporter.tar.gz"
      dest: "/opt/"
      remote_src: yes
      creates: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

  - name: Move binary to /usr/local/bin
    copy:
      remote_src: yes
      src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
      dest: /usr/local/bin/node_exporter
      mode: '0755'

  - name: Create systemd service file
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: '0644'

  - name: Reload systemd
    systemd:
      daemon_reload: yes

  - name: Enable and start Node Exporter
    systemd:
      name: node_exporter
      enabled: yes
      state: started
