---
# - name: Initialisation d'une VM
#   hosts: all
#   become: true
#   vars_files:
#     - roles/init-vm/vars/main.yml
#   roles:
#     - init-vm

# - name: Installation de Keycloak
#   hosts: all
#   become: true
#   roles:
#     - keycloak

# - name: Installation de Nginx
#   hosts: all
#   become: true
#   roles:
#     - nginx

# - name: Installation de Node Exporter
#   hosts: all
#   become: true
#   roles:
#     - node-exporter

# - name: Installation de cadvisor
#   hosts: all
#   become: true
#   roles:
#     - cadvisor

# - name: Installation de Grafana-Prometheus
#   hosts: all
#   become: true
#   roles:
#     - grafana-prom

- name: Initialisation d'une VM
  hosts: keycloak_nginx
  become: true
  vars_files:
    - roles/init-vm/vars/main.yml
  roles:
    - init-vm


# - name: Installation de Grafana
#   hosts: grafana
#   become: true
#   roles:
#     - grafana-prom

# - name: Installation de Node Exporter
#   hosts: all
#   become: true
#   roles:
#     - node-exporter

# - name: Installation de cadvisor
#   hosts: grafana:keycloak_nginx
#   become: true
#   roles:
#     - cadvisor

# - name: Installation de PostgreSQL et Redis
#   hosts: postgres_redis
#   become: true
#   roles:
#     - postgres
#     - redis

# - name: Installation de GitLab
#   hosts: gitlab
#   become: true
#   roles:
#     - gitlab

- name: Installation de Keycloak et Nginx
  hosts: keycloak_nginx
  become: true
  roles:
    - keycloak
    - nginx


