---
  - name: Mettre à jour tous les paquets
    dnf:
      name: "*"
      state: latest

  - name: Activer le dépôt EPEL 
    dnf:
      name: epel-release
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Installer les paquets de base
    dnf:
      name:
        - vim
        - curl
        - sudo
        - htop
      state: present
  - name: Installer python3-requests
    dnf:
      name: python3-requests
      state: present
    become: true

  - name: Définir le hostname
    hostname:
      name: "{{ hostname_name }}"

  - name: Ajouter le hostname dans /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "127.0.1.1 {{ hostname_name }}"
      state: present
      create: yes
