all:
  children:
    keycloak_nginx:
      vars:
        install_docker: true
      hosts:
        51.38.232.14:
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          hostname_name: keycloak-nginx
    gitlab:
      hosts:
        152.228.172.167:
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          hostname_name: gitlab-1
        54.36.101.87:
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          hostname_name: gitlab-2
    postgres_redis:
      hosts:
        51.38.239.212:
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          hostname_name: postgres-redis
    grafana:
      vars:
        install_docker: true
      hosts:
        51.38.234.58:
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          hostname_name: grafana-prometheus

