---
  - name: Lancer cAdvisor en conteneur
    docker_container:
      name: cadvisor
      image: gcr.io/cadvisor/cadvisor:latest
      restart_policy: always
      ports:
        - "8081:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      state: started
      privileged: true
