---
- name: Installer NFS
  dnf:
    name: nfs-utils
    state: present
    update_cache: yes

- name: Activer et démarrer le service NFS
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: Créer les dossiers nécessaires
  file:
    path: "{{ item }}"
    state: directory
    owner: rocky
    group: rocky
    mode: '0755'
  loop:
    - /srv/gitlab-nfs/repositories
    - /srv/gitlab-nfs/uploads
    - /srv/gitlab-nfs/shared
    - /srv/gitlab-nfs/builds

- name: Configurer les exports
  copy:
    dest: /etc/exports
    content: |
      /srv/gitlab-nfs/repositories 152.228.172.167(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/repositories 54.36.101.87(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/uploads      152.228.172.167(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/uploads      54.36.101.87(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/shared       152.228.172.167(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/shared       54.36.101.87(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/builds       152.228.172.167(rw,sync,no_root_squash,no_subtree_check)
      /srv/gitlab-nfs/builds       54.36.101.87(rw,sync,no_root_squash,no_subtree_check)

- name: Appliquer les exports
  command: exportfs -ra
